#!/bin/sh

STAGED_GO_FILES=$(git diff --cached --name-only -- '*.go')

# Check for no go files
[ -z "$STAGED_GO_FILES" ] && exit 0

# Format all staged go files
for file in $STAGED_GO_FILES; do
  gofmt -w "$file"
  git add "$file"
done

exit 0

