repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-added-large-files
      - id: check-executables-have-shebangs
      - id: check-merge-conflict
  - repo: https://github.com/dnephin/pre-commit-golang
    rev: v0.5.1
    hooks:
      - id: go-fmt
      - id: go-mod-tidy
# -   repo: local
#     hooks:
#       -   id: yarn-format"
#           name: "yarn format"
#           entry: ./scripts/precommit-yarn-format.sh
#           language: script
#           always_run: true
