version: "3"

tasks:
  run:
    cmds:
      - cd server/src && air run main.go

  test-all:
    cmds:
      - cd server && go test ./tests/...

  connect:
    cmds:
      - psql -U postgres -W -p 5432 -h localhost -d legacy

  format:
    cmds:
      - cd server && go fmt ./... && cd ../client && yarn format
  
  insertData:
    cmds:
      - cd server/src/migrations && psql -h localhost -U postgres -d legacy -f data.sql