version: "3"

tasks:
  run:
    cmds:
      - cd server/src && air run main.go

  test-all:
    cmds:
      - cd server && go test ./tests/...

  docker:
    cmds:
      - cd scripts && ./verify_os.sh

  connect:
    cmds:
      - psql -U postgres -W -p 5432 -h localhost -d legacy

  format:
    cmds:
      - cd server && go fmt ./... && cd ../client && yarn format
